name: 'Be good at what you do!'
favicon: null
layout_spectrum: 0.00513
typography_spectrum: 0.30865
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f1fff0'
    - '#98b8c1'
    - '#f85218'
    - '#f3a281'
    - '#6996b5'
  brandStrength: 0.1875
  lightness: 0.875
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
